# Site settings
title: Connor McKelvey
email: connormckelvey@gmail.com
description: I am a Software Engineer living in Boulder, CO. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.connormckelvey.com" # the base hostname & protocol for your site
twitter_username: cssddict
github_username:  connormckelvey

markdown: kramdown

exclude:
  - divshot.json
  - divshot-debug.log
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed
