# Site settings
title: Connor McKelvey
email: connormckelvey@gmail.com
description: I am a front-end developer living in Orlando, FL. I have a thing for Javascript and I love accessibility. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: cssddict
github_username:  connormckelvey

highlighter: pygments
# Build settings
markdown: kramdown

exclude:
  - divshot.json
  - divshot-debug.log